const RELEASE = {
  "version": "7.9.0-dev.1",
  "appBuild": "47695610d731e02b40ed30e0e07e59e66cb0cfe3d52f446df2bef07156f8a844",
  "id": "102775ba3c83accfb66cc6aa",
  "protocol": 1,
  "files": [
    {
      "url": "./player_almanac.html",
      "sha256": "f7df89fa2d321310c5bf820ffab47aa94599e7f8774d0097ef633e2e24fad4f8",
      "bytes": 758923
    },
    {
      "url": "./index.html",
      "sha256": "00ae66ca64b8ca78e537b0feee9e0e10835b5006c99fe59de61cdfdaf553fb06",
      "bytes": 338
    },
    {
      "url": "./manifest.json",
      "sha256": "0e801f713ae452aca2e9656c3b8f3b01cefa2c088932b9e39ee9af9d61191a18",
      "bytes": 1001
    },
    {
      "url": "./icons/icon-192.png",
      "sha256": "80f6a9b842d63c5b3995273d67fd87d3fd5b47308193eb32a62fa82b93691cca",
      "bytes": 65778
    },
    {
      "url": "./icons/icon-512.png",
      "sha256": "58d892afc2fa29e15b61b5c2e93d784683864fd52d8fe722ad3508d407e75304",
      "bytes": 287447
    },
    {
      "url": "./icons/maskable-192.png",
      "sha256": "487386529878a3b8d102097ba9d71819b11372979644a79601d9381e5e7c205a",
      "bytes": 17354
    },
    {
      "url": "./icons/maskable-512.png",
      "sha256": "b5c348ca7d02dbe2b9e9177a2e784ea65427d4ecc498270672a8a25d2141063a",
      "bytes": 81631
    },
    {
      "url": "./fonts/Manrope.ttf",
      "sha256": "d0639be45d0af36e798172419d7bd173c4bd4f29e2b76cbb69db1d11bf8b0a40",
      "bytes": 165420
    },
    {
      "url": "./fonts/Fraunces.ttf",
      "sha256": "177ff6c0f14e5550a3c624247cd1189611d4eb65d000b14944c63d967958abbb",
      "bytes": 360440
    }
  ]
};
/* RELEASE is generated by tools/build.mjs. Canonical character storage is never
 * accessed here. A release is exposed only after every required byte is verified.
 * Upgrades use normal waiting-worker activation AFTER all old clients close:
 * there is deliberately no skipWaiting/forced reload race with an unready tab. */
'use strict';
const PREFIX = 'player-almanac:' + self.registration.scope + ':';
const CACHE = PREFIX + RELEASE.version + ':' + RELEASE.id;
const META = new URL('./__pa_release_verified__', self.registration.scope).href;
const APP = new URL('./player_almanac.html', self.registration.scope).href;
const INDEX = new URL('./index.html', self.registration.scope).href;
const ROOT = self.registration.scope;
const FILES = RELEASE.files.map(file => ({ ...file, absolute: new URL(file.url, self.registration.scope).href }));
const byURL = new Map(FILES.map(file => [file.absolute, file]));
const digest = async bytes => [...new Uint8Array(await crypto.subtle.digest('SHA-256', bytes))].map(b => b.toString(16).padStart(2, '0')).join('');
async function verified(response, file) {
  if (!response || !response.ok || response.type === 'opaque') throw new Error('Asset unavailable: ' + file.url);
  const bytes = await response.clone().arrayBuffer();
  if (bytes.byteLength !== file.bytes || await digest(bytes) !== file.sha256) throw new Error('Release mismatch: ' + file.url);
  return response;
}
async function download(file) {
  const controller = new AbortController(), timer = setTimeout(() => controller.abort(), 20000);
  try { return await verified(await fetch(new Request(file.absolute, { cache: 'reload', credentials: 'same-origin', signal: controller.signal })), file); }
  finally { clearTimeout(timer); }
}
async function status({ verifyBytes = true } = {}) {
  if (!await caches.has(CACHE)) return { ready: false, missing: FILES.map(f => f.url) };
  const cache = await caches.open(CACHE), missing = [];
  let metadata; try { metadata = await (await cache.match(META))?.json(); } catch {}
  if (metadata?.id !== RELEASE.id) missing.push('verification-marker');
  for (const file of FILES) {
    try { const response = await cache.match(file.absolute); if (!response) throw new Error(); if (verifyBytes) await verified(response, file); }
    catch { missing.push(file.url); }
  }
  return { ready: missing.length === 0, missing, version: RELEASE.version, appBuild: RELEASE.appBuild, releaseId: RELEASE.id, cache: CACHE };
}
self.addEventListener('install', event => event.waitUntil((async () => {
  if ((await status()).ready) return;
  const existed = await caches.has(CACHE), cache = await caches.open(CACHE);
  try {
    // Do not mutate the currently active release cache. Each release ID has its
    // own namespace. Download/verify all responses before adding a ready marker.
    const resources = await Promise.all(FILES.map(download));
    for (let i = 0; i < FILES.length; i++) await cache.put(FILES[i].absolute, resources[i]);
    await cache.put(META, new Response(JSON.stringify({ ...RELEASE, installedAt: Date.now() }), { headers: { 'Content-Type': 'application/json' } }));
    if (!(await status()).ready) throw new Error('Precache read-back failed');
  } catch (error) { if (!existed) await caches.delete(CACHE); throw error; }
})()));
self.addEventListener('activate', event => event.waitUntil((async () => {
  if (!(await status()).ready) throw new Error('Cannot activate an incomplete release');
  // Retain the current release and two verified previous releases for diagnosis.
  // Normal activation means controlled clients of the replaced worker are gone.
  const candidates = [];
  for (const name of await caches.keys()) if (name.startsWith(PREFIX) && name !== CACHE) {
    try { const meta = await (await (await caches.open(name)).match(META))?.json(); if (meta?.installedAt) candidates.push({ name, at: meta.installedAt }); }
    catch {}
  }
  candidates.sort((a, b) => b.at - a.at);
  for (const old of candidates.slice(2)) await caches.delete(old.name);
  await self.clients.claim();
})()));
self.addEventListener('fetch', event => {
  if (event.request.method !== 'GET') return;
  const url = new URL(event.request.url); if (url.origin !== new URL(ROOT).origin) return;
  url.hash = ''; url.search = '';
  const key = url.href === ROOT ? APP : url.href;
  const file = byURL.get(key); if (!file) return;
  event.respondWith((async () => {
    const cache = await caches.open(CACHE), cached = await cache.match(key);
    if (cached) return cached;
    // Evicted asset repair must match the SAME release. Never put arbitrary new
    // network HTML into an old release cache, even after a fresh deployment.
    try { const response = await download(file); await cache.put(key, response.clone()); return response; }
    catch {
      return new Response('Player Almanac: this installed release is incomplete. Reconnect, prepare an update, close all Player Almanac tabs, then reopen. Your character storage has not been changed. / Diese installierte Version ist unvollstaendig. Verbinde dich, bereite ein Update vor, schliesse alle Almanac-Fenster und oeffne die App erneut. Charakterdaten wurden nicht geaendert.', { status: 503, headers: { 'Content-Type': 'text/plain;charset=utf-8', 'Cache-Control': 'no-store' } });
    }
  })());
});
async function scopedClients() {
  const scope = new URL(ROOT);
  return (await self.clients.matchAll({ type: 'window', includeUncontrolled: true })).filter(client => { try { const url = new URL(client.url); return url.origin === scope.origin && url.pathname.startsWith(scope.pathname); } catch { return false; } });
}
function ask(client, data, timeout = 12000) {
  return new Promise(resolve => {
    const channel = new MessageChannel(), timer = setTimeout(() => { channel.port1.close(); resolve({ ok: false, reason: 'unresponsive', clientId: client.id }); }, timeout);
    channel.port1.onmessage = event => { clearTimeout(timer); channel.port1.close(); resolve({ ...event.data, clientId: client.id }); };
    try { client.postMessage(data, [channel.port2]); } catch { clearTimeout(timer); resolve({ ok: false, reason: 'unreachable', clientId: client.id }); }
  });
}
let preparing = null;
self.addEventListener('message', event => {
  const data = event.data || {}, reply = response => event.ports?.[0]?.postMessage(response);
  if (data.type === 'PA_STATUS') event.waitUntil(status().then(reply).catch(error => reply({ ready: false, error: error.message })));
  if (data.type === 'PA_PREPARE_ALL') event.waitUntil((async () => {
    if (preparing) { reply({ ok: false, reason: 'already-preparing' }); return; }
    const updateId = preparing = crypto.randomUUID(); let clients = [];
    try {
      if (!(await status()).ready) throw new Error('offline-not-ready');
      clients = await scopedClients();
      const results = await Promise.all(clients.map(client => ask(client, { type: 'PA_PREPARE_UPDATE', updateId, protocol: 1, version: RELEASE.version, appBuild: RELEASE.appBuild })));
      const after = await scopedClients(), originalIds = new Set(clients.map(client => client.id));
      if (results.some(result => !result.ok || result.protocol !== 1) || after.some(client => !originalIds.has(client.id))) {
        for (const client of after) client.postMessage({ type: 'PA_ABORT_PREPARE', updateId });
        reply({ ok: false, reason: 'clients-not-ready', clients: results, newClients: after.filter(c => !originalIds.has(c.id)).length }); return;
      }
      // ACK means last-good data AND any outstanding recoverable drafts are
      // durable; it does not mean every draft became a committed character.
      for (const client of after) client.postMessage({ type: 'PA_CLOSE_TO_UPDATE', updateId, version: RELEASE.version });
      reply({ ok: true, closeAllRequired: true, clients: results.length, version: RELEASE.version });
    } catch (error) {
      for (const client of clients) client.postMessage({ type: 'PA_ABORT_PREPARE', updateId });
      reply({ ok: false, reason: error.message });
    } finally { preparing = null; }
  })());
  // Old SKIP_WAITING messages are intentionally ignored. A nonparticipating old
  // tab must close; its failure to ACK can never authorize forced activation.
});
